# Generated by Django 5.1.4 on 2025-06-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuIngredientMaster', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='reciperequirement',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
