# Generated by Django 5.1.4 on 2025-06-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuIngredientMaster', '0002_ingredient_total_price_reciperequirement_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeRequirement',
            new_name='RecipeRequirements',
        ),
    ]
