# Generated by Django 5.1.4 on 2025-06-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuIngredientMaster', '0004_rename_price_reciperequirements_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
