# Generated by Django 5.1.4 on 2025-06-27 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuIngredientMaster', '0005_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date purchased'),
        ),
    ]
