# Generated by Django 5.1.4 on 2025-07-04 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuIngredientMaster', '0007_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date purchased'),
        ),
    ]
