# Generated by Django 5.1.4 on 2025-07-04 14:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MenuIngredientMaster', '0009_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='acquiredIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('quantity', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=15)),
                ('unit_price', models.FloatField(default=0)),
                ('total_price', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date purchased')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='timestamp',
        ),
    ]
