# Generated by Django 5.1.4 on 2025-07-10 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MenuIngredientMaster', '0010_acquiredingredients_remove_ingredient_timestamp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='acquiredIngredients',
            new_name='acquiredIngredient',
        ),
    ]
